name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'feat/')

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install flake8
        run: pip install flake8

      - name: Lint Python files
        run: |
          if find . -name "*.py" | grep -q .; then
            flake8 . --max-line-length=120 --exclude=.git
          else
            echo "No Python files found — skipping lint"
          fi

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.event.pull_request.head.ref, 'feat/')

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt — skipping install"
          fi

      - name: Run pytest
        run: |
          if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
            pip install pytest && pytest -v
          else
            echo "No test files found — placeholder pass"
          fi
